<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXD6vUqq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXD6vUqq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXD6vUqq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXD6vUqq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXD6vUqq\App_KernelDevDebugContainer([
    'container.build_hash' => 'XD6vUqq',
    'container.build_id' => '645aba44',
    'container.build_time' => 1580566730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXD6vUqq');
